name: Lint
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
#       Removing Prettify Code Test until Bug is fixed: https://github.com/creyD/prettier_action
#       - name: Prettify code
#         uses: creyD/prettier_action@v4.3
#         with:
#           prettier_options: --check src
#           prettier_plugins: '@trivago/prettier-plugin-sort-imports prettier-plugin-tailwindcss'
